name: 'Upload app to TdA'
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  upload_to_TdA:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get Deploy Access
        id: deployAccess
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://auth.registry.tourdeapp.eu/staging-auth'
          method: 'POST'
          data: '{"team_secret": "${{ secrets.TEAM_SECRET }}"}'

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          registry: registry.tourdeapp.eu
          username: tourdeapp
          password: ${{ fromJson(steps.deployAccess.outputs.response).key }}

      - name: Load and push image
        env:
          IMAGE: ${{ fromJson(steps.deployAccess.outputs.response).name }}
        run: |
          cat ${{ inputs.image_path }} | docker load
          docker tag ${{ inputs.image_name }} $IMAGE
          docker push $IMAGE
